name: Java with Gradle

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4.1.6

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: temurin

      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew exportJar

      - name: Upload a the exported jars
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ExportedJars
          path: |
            controller/build/libs/**.jar
            server/build/libs/**.jar