name: Java with Gradle

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      
        

      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew exportJar
          

      - name: Upload a the exported jars
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Controller
          path: controller/build/libs/**.jar

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: Server
          path: server/build/libs/**.jar